### PR TITLE
bump version of deps from snapshot to release (IdP 3.2.0)

### PR DESCRIPTION
**Pull request by helix84**

### CODE REVIEW

**Comment by mmoayyed** [comment]
Have you gone through all configuration and made sure nothing else has changed in the idp webapp?

**Comment by helix84** [comment]
No, not thoroughly,  but master branch was broken anyway (failed to build due to unavailable snapshot dependencies).

**Comment by mmoayyed** [comment]
True. Not sure what happened to the jenkins build of the idp but I'll get this merged and work on updating other files. Thank you.

**Comment by helix84** [comment]
> Not sure what happened to the jenkins build of the idp

Travis just had the snapshot versions cached. On a local system, you would run mvn with -U to resolve that.

Though it's weird I don't see .m2 being cached in .travis.yml. Not sure what the defaults are nowadays.
https://docs.travis-ci.com/user/caching/

**Pull request merged**
